### PR TITLE
yquake2-1.0.4: Add vulkan profile

### PR DESCRIPTION
**Pull request by 0lvin**
yQuake2 is recently released with unofficial vulkan support. 

Could you please review?

### CODE REVIEW

**Comment by 0lvin** [comment]
@michaellarabel Could you please review? Should I add some additional dependencies/fixes? 

Thank you.

**Comment by michaellarabel** [comment]
Is there any way to increase the intensity of the demo/test? And when checking the test profile earlier, seems to be capped at 999 FPS. So when having tried with various modern GPUs, I wasn't able to see much/any difference really.

**Comment by 0lvin** [comment]
Could you try with `r_retexturing` to 2, r_msaa_samples to 8, r_anisotropic to 16? 

r_retexturing=2 will make default textures bigger in vulkan. msaa = 8 is maximum common value that my current system run without reset to default values. 

I am not sure that such values is safe for most of cases.

**Comment by 0lvin** [comment]
5k resolution looks as really slow, maybe its in some way specific to RADV(or vulkan render) but in vulkan i have only 5fps vs 160fps with opengl.

**Comment by michaellarabel** [comment]
Thanks, those options seem to make it more demanding. Merged now as pts/yquake-1.1.0 given the major Yquake2 version bump. Also added vulkan-development to the external dependencies list.

**Comment by 0lvin** [comment]
Thank you!

**Pull request closed without merging**
