### PR TITLE
Update dav1d profile with 0.2.1 release

### PR DESCRIPTION
**Pull request by EwoutH**
Prepares a test profile for dav1d 0.2.0 release. Changes profile number to 2.0.0, changes from 1.1.0:
 - [x] Update to dav1d 0.2.0
 - [x] Add Chimera 8-bit and 10-bit test video's
 - [x] Add -q (silent) and --filmgrain 0 (disable filmgrain) parameters

And some small changes not affecting performance:
 - [x] Update FFmpeg to 4.1.1 (only used for conversion to .ivf)
 - [x] Remove .webm and .mp4 files after they are muxed to .ivf

**Todo:**
- [ ] Switch result definition from time to FPS 
- [ ] Add SHA256 and MD5 hashes for the Chimera video's
- [x] Update dav1d 0.2.1 release
- [x] Add SHA256 and MD5 hashes for dav1d 0.2.1

### CODE REVIEW

**Comment by EwoutH** [comment]
@michaellarabel Could you help with redefine the results-definition? I would like to change it from time (seconds) to speed (frames/second). The Elecard video's have 3604 frames (so it should be 3604/sys.time) and the Chimera video's have 8929 frames (8929/sys.time).

**Comment by EwoutH** [comment]
@michaellarabel dav1d 0.2.0 [just got tagged](https://code.videolan.org/videolan/dav1d/tags/0.2.0) and I uploaded the download link. Could you take a look at the results definition?

**Comment by michaellarabel** [comment]
@EwoutH are there any plans to add FPS reporting to dav1d itself? That would ideally be the best place to have it, similar to the reporting offered by SVT*, x264/x265, vpxenc, etc. Otherwise I can do some workarounds in the test profile to accommodate the FPS reporting in the test profile itself, but would be better if dav1d supported such output / performance stats itself.

**Comment by EwoutH** [comment]
Not that I know of.

Aside from that, a 0.2.1 is coming with an unscheduled API change to fix some unexpected behavior. Best to wait for that.

Enjoyed the inclusion of dav1d in the GCC 9 compiler tuning benchmarks btw!

**Comment by EwoutH** [comment]
@michaellarabel Updated to dav1d 0.2.1. Chimera video where to big for my hash generator, could you add those?

**Comment by EwoutH** [comment]
@michaellarabel dav1d doesn't have a clock built in, it just decodes a frame as fast as possible.

Would it be very difficult to divide the score by a number of frames before reporting?

**Comment by michaellarabel** [comment]
Not difficult but not necessarily most accurate since the timer would also include the (albeit brief) time of dav1d startup/shutdown, etc. If there are no plans to add clock support in the near future to dav1d, I can go ahead and add it to the test profile itself.

**Comment by EwoutH** [comment]
@michaellarabel I see your concern, but it wouldn't be different from the current situation (where also the time is reported), right? The test sequences should be long enough to make the difference negligible.

**Comment by michaellarabel** [comment]
To some extent, yes. But when showing a 'FPS' value, there is the desire when looking at 'FPS' metrics between different encoders/decoders in wanting to compare those values. Most of the other test profiles of the other encoders/decoders are reporting the FPS value from the program itself. But anyhow will try to find the time later today to review these latest dav1d changes and add in the FPS conversion bit.

**Comment by EwoutH** [comment]
Replaced by #79.

**Pull request closed without merging**
