### PR TITLE
pts/twtk-1.0.0: Initial commit of Total War: Three Kingdoms

### PR DESCRIPTION
**Pull request by ardickerson64**
Initial commit of test profile for Total War: Three Kingdoms.

### CODE REVIEW

**Comment by michaellarabel** [comment]
Thanks, evaluating it now and should have it on OpenBenchmarking.org shortly.

**Comment by michaellarabel** [comment]
The test profile is working out. The only issue I am seeing is on first run the message box first appearing over "Mods have been disabled". Have you ran into this issue? Will check to see if the settings/preferences allow for bypassing that message box interruption.

**Comment by michaellarabel** [comment]
The test profile is now available via OpenBenchmarking.org so clients can now run `phoronix-test-suite benchmark twtwk`

I did try toggling the SpecificationAlerts within the preferences XML to try to workaround the "Mods have been disabled" message box but so far no luck. I assume the disabling of mods via the settings file is being done intentionally to avoid potential performance interference from any mods?

**Comment by ardickerson64** [comment]
Hmmm...

I ran into the same mod warning but was able to silence it via the SpecificationAlerts in preferences; however, I just took my Steam online and notice there's a game update.

I'll look into getting that dialog silenced.

**Comment by ardickerson64** [comment]
New pull request submitted for the fix.

Apologies for the messy commit history; needed to make some conformance changes.

**Pull request merged**
