### PR TITLE
Update SVT-HEVC profile

### PR DESCRIPTION
**Pull request by EwoutH**
New version of the SVT-HEVC profile. 

@michaellarabel Could you zip and upload a new version of [SVT-HEVC](https://github.com/OpenVisualCloud/SVT-HEVC/commits/master) to http://www.phoronix-test-suite.com/benchmark-files/ and add the hashes to the `downloads.xml`?

### CODE REVIEW

**Comment by michaellarabel** [comment]
Is there something new in particular at the moment for SVT-HEVC? I see they had the 1.4 release in August and they actually do tagged releases unlike some of the other SVT encoders (at least for now). So just wondering if there is something exciting in SVT-HEVC Git as opposed to just waiting for the next release? Thanks.

**Comment by EwoutH** [comment]
There are some significant changes, also in the build system. I would suggest taking the master branch now, and then switching to releases starting at the next release.

**Comment by EwoutH** [comment]
@michaellarabel Updated the profile to the brand new 1.4.1 release

**Comment by michaellarabel** [comment]
Thanks, will get it tested and uploaded soon. PTS 9.0 release week so a bit busy.

@EwoutH as you happen to be involved with SVT to some extent, do you happen to know about any plans for them to provide official Windows binaries of their releases? So far they just seem to do Windows binaries with their SVT-AV1 releases but sadly not HEVC or VP9. It would be convenient if they did to avoid the mess of building it on Windows and most Windows users just using official binaries anyways.

**Comment by michaellarabel** [comment]
The SVT-HEVC test profile is now updated and includes Windows support added in and other changes.

**Comment by ganeshgit** [comment]
Is there a bug in the way we execute the bmk?
To get it working, we had to add 
 -thread-count $(nproc)
 
./SVT-HEVC/Bin/Release/SvtHevcEncApp **-thread-count $(nproc)**  -encMode 1 -i Bosphorus_1920x1080_120fps_420_8bit_YUV.yuv -w 1920 -h 1080

**Pull request closed without merging**
