### PR TITLE
[RFC] pts/build-clash-1.0.0:  new

### PR DESCRIPTION
**Pull request by deepfire**
Status:  request for comments -- I don't have PTS installed, so I didn't test it.

Add timed building of `clash-lang` (https://clash-lang.org/) using GHC 8.10.1 and `compilation-benchmark`, that is based on reproducible builds machinery supplied by the Nix package manager (https://nixos.org/download.html).

### CODE REVIEW

**Comment by michaellarabel** [comment]
Thanks and congrats on your first test profile work. I have this test profile with a few tweaks now running. Quick question is what is the expected runtime on build-clash? So far it's at 25 minutes on one of my fastest boxes, so just curious while waiting for it to finish in case I have something misconfigured.

Will be around with more feedback once working through the testing process.

**Comment by michaellarabel** [comment]
I've merged an improved version of the patch. The key changes include:

- Rather than doing the Git clone, just hosting a static .tar.xz copy. That is preferred since then PTS / Phoromatic can do automatic caching of that for users behind-the-firewall and other corporate environments.

- Tweaked the XML file for SystemDependencies = ghc, jq, so that this test profile will install the necessary dependencies out-of-the-box. Tested that it works fine on a clean Ubuntu 20.04 install.

- To the install script have it automatically setting up Nix automatically.

I think it should be working well, thanks!

Running a few tests on it now @ https://openbenchmarking.org/test/pts/build-clash-1.0.0

**Comment by deepfire** [comment]
> Thanks and congrats on your first test profile work.

Thank you!

>  I have this test profile with a few tweaks now running. Quick question is what is the expected runtime on build-clash?
> So far it's at 25 minutes on one of my fastest boxes, so just curious while waiting for it to finish in case I have something misconfigured.

Ok, the intent was that it runs a single iteration around 11 minutes, but I discovered a bug, where it was ignoring `--iterations 1` and was running for 3 iterations, actually.

Fix pushed -- and my apologies for the silly mistake.

> Will be around with more feedback once working through the testing process.

**Comment by deepfire** [comment]
> Thanks and congrats on your first test profile work.

Thank you, @michaellarabel !

>  I have this test profile with a few tweaks now running. Quick question is what is the expected runtime on build-clash?
> So far it's at 25 minutes on one of my fastest boxes, so just curious while waiting for it to finish in case I have something misconfigured.

Ok, the intent was that it runs a single iteration around 11 minutes, but I discovered a bug, where it was ignoring `--iterations 1` and was running for 3 iterations, actually.

Fix pushed -- and my apologies for the silly mistake.

> Will be around with more feedback once working through the testing process.

**Pull request closed without merging**
