### PR TITLE
Update dav1d profile

### PR DESCRIPTION
**Pull request by EwoutH**
- Updates to dav1d 0.4.0
 - Add Chimera test cases, including 10-bit

Incorporates some features of #70.

@michaellarabel If you could find a way to report the frame rate instead of time that would be amazing. The Elecard video's contain 3604 frames, the Chimera video's 8929 frames. So divide that number by `sys.time` to get fps.

Also, maybe it would be good to download only the video's for the tests that are being run (if only Elecard is run, don't download Chimera i.e.).

### CODE REVIEW

**Comment by michaellarabel** [comment]
@EwoutH dav1d should *finally* have FPS reporting support... Neeed to see if it got in 0.4 as IIRC, it was merged but then reverted but may have got back in. I think this was the earlier support ticket about it - https://code.videolan.org/videolan/dav1d/merge_requests/670

I wanted to avoid just dividing total time by frames due to the (albeit miniscule) startup/close times and any other potential disturbances, but at least dav1d should now have FPS reporting or soon.

All tests will download all relevant files for their platform at install-time to help with behind-the-firewall/offline use-cases among other factors rather than trying to punt some downloading tasks to run-time.

**Comment by EwoutH** [comment]
Totally forgot that got implemented. I removed the `-q` switch, dav1d now reports fps continuously in the following format:

`Decoded 8929/8929 frames (100.0%) - 220.56/23.98 fps (9.20x)`

**Comment by michaellarabel** [comment]
An updated dav1d test profile using dav1d w/ FPS reporting and supporting Chimera video input options is now available. Thanks.

**Comment by EwoutH** [comment]
Thanks for merging! Could you add a dav1d Git profile with both Chimera video's to [linuxbenchmarking.com](http://linuxbenchmarking.com/?video-benchmarks)? If you include an AVX2 processor and a non-AVX2 processor, we could cover 8-bit SSSE3, 8-bit AVX2, 10-bit SSSE3 and 10-bit AVX2 performance improvements!

**Comment by EwoutH** [comment]
@michaellarabel Hey, quick request. The first AVX-512 assembly targeted at Ice Lake (using VNNI and VBMI) has been [merged into dav1d](https://code.videolan.org/videolan/dav1d/merge_requests/883). Any chance you can do a quick comparison of dav1d 0.5.0 to the current master branch on an Ice Lake system?

**Comment by EwoutH** [comment]
@michaellarabel dav1d 0.6.0 will be tagged very soon! Is has major speedups in 10-bit decoding on Arm64 thanks to the partnership with Netflix and amazing work of Martin Storsjö. It also features more AVX-512 assembly targeting Ice Lake. Important is that by default only SIMD up to AVX2 is used, you need to add `--cpumask avx512icl` to the command line to run with AVX-512 Ice Lake assembly.

**Comment by EwoutH** [comment]
dav1d 0.8.2 was [released today](https://code.videolan.org/videolan/dav1d/-/releases). It's a medium sized update, and combined with the changes in 0.8.1 I think it warrants a new test profile.

It should accelerate the Chimera 10-bit video quite a bit on desktop processors, with the AVX2 assembly for high-bit depth.

> Changes for 0.8.2 'Eurasian hobby':
> -----------------------------------
> 0.8.2 is a middle-size update of the 0.8.0 branch:
>  - ARM32 optimizations for ipred and itx in 10/12bits,
>    completing the 10b/12b work on ARM64 and ARM32
>  - Give the post-filters their own threads
>  - ARM64: rewrite the wiener functions
>  - Speed up coefficient decoding, 0.5%-3% global decoding gain
>  - x86 optimizations for CDEF_filter and wiener in 10/12bit
>  - x86: rewrite the SGR AVX2 asm
>  - x86: improve msac speed on SSE2+ machines
>  - ARM32: improve speed of ipred and warp
>  - ARM64: improve speed of ipred, cdef_dir, cdef_filter, warp_motion and itx16
>  - ARM32/64: improve speed of looprestoration
>  - Add seeking, pausing to the player
>  - Update the player for rendering of 10b/12b
>  - Misc speed improvements and fixes on all platforms
>  - Add a xxh3 muxer in the dav1d application
> 
> Changes for 0.8.1 'Eurasian hobby':
> -----------------------------------
> 0.8.1 is a minor update on 0.8.0:
>  - Keep references to buffers valid after dav1d_close(). Fixes a regression
>    caused by the picture buffer pool added in 0.8.0.
>  - ARM32 optimizations for 10bit bitdepth for SGR
>  - ARM32 optimizations for 16bit bitdepth for blend/w_masl/emu_edge
>  - ARM64 optimizations for 10bit bitdepth for SGR
>  - x86 optimizations for wiener in SSE2/SSSE3/AVX2

**Comment by michaellarabel** [comment]
Indeed as v0.8.2 has some interesting performance changes, I've updated the pts/dav1d test profile against it.

https://openbenchmarking.org/test/pts/dav1d

In the future if you can open it as a new issue, that would make for easier tracking. Thanks.

**Pull request closed without merging**
