### PR TITLE
Add build-linux-kernel v1.9.0.

### PR DESCRIPTION
**Pull request by busykai**
Bump the kernel version to 4.17. Using kernel 4.13 breaks on system with
gcc v8.x.

@michaellarabel, please take a look. If some other process should be used, please let me know.

### CODE REVIEW

**Comment by michaellarabel** [comment]
Hi @busykai is there a reason you went for 4.17 rather than the newer 4.18? I am happy to adjust the test to 4.18 on my end, just wasn't sure if there was a reason you opted for 4.17 with 4.18 already being out instead.

**Comment by busykai** [comment]
@michaellarabel, no specific reason, just took the kernel i know compiles. :) i'll switch to the 4.18 kernel later tonight. thanks!

**Comment by michaellarabel** [comment]
No worries. I already have a 4.18 local test profile so I will go ahead and upload that shortly.

**Comment by michaellarabel** [comment]
I've uploaded my local pts/build-linux-kernel-1.9 build now to OpenBenchmarking.org and is available to PTS clients and has been tested on Clear and Ubuntu.

It's adjusted against upstream 4.18 plus adds in some newer dependencies needed since for the kernel like openssl header files and bison and flex. It also makes a few tweaks to the defconfig around the ORC unwinder to avoid having to ensure libelf is present on the distribution.

**Comment by busykai** [comment]
Thank you, @michaellarabel !

**Pull request closed without merging**
